// Copyright 2026 Zyno
// SPDX-License-Identifier: Apache-2.0
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *IngressTranslation) DeepCopyInto(out *IngressTranslation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *IngressTranslation) DeepCopy() *IngressTranslation {
	if in == nil {
		return nil
	}
	out := new(IngressTranslation)
	in.DeepCopyInto(out)
	return out
}

func (in *IngressTranslation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *IngressTranslationList) DeepCopyInto(out *IngressTranslationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]IngressTranslation, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *IngressTranslationList) DeepCopy() *IngressTranslationList {
	if in == nil {
		return nil
	}
	out := new(IngressTranslationList)
	in.DeepCopyInto(out)
	return out
}

func (in *IngressTranslationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *IngressTranslationStatus) DeepCopyInto(out *IngressTranslationStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
	if in.GeneratedResources != nil {
		out.GeneratedResources = make([]ResourceReference, len(in.GeneratedResources))
		copy(out.GeneratedResources, in.GeneratedResources)
	}
	if in.Issues != nil {
		out.Issues = make([]TranslationIssue, len(in.Issues))
		copy(out.Issues, in.Issues)
	}
}
