apiVersion: v2
name: ingress-nginx-gateway-bridge
description: Live ingress-nginx compatibility bridge for NGINX Gateway Fabric
type: application
version: 0.1.3
appVersion: 0.1.3
home: https://github.com/zyno-io/ingress-nginx-gateway-bridge
sources:
  - https://github.com/zyno-io/ingress-nginx-gateway-bridge
maintainers:
  - name: Zyno
    url: https://zyno.io
annotations:
  artifacthub.io/license: Apache-2.0
